# Generated by Django 5.2.1 on 2025-06-01 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='category',
            field=models.CharField(choices=[('Недвижимость', 'Недвижимость'), ('Транспорт', 'Транспорт'), ('Личные вещи', 'Личные вещи'), ('Электроника', 'Электроника')], max_length=100, verbose_name='Категория'),
        ),
    ]
